### PR TITLE
Y24-314: Handle relatives that are V2::Assets

### LINKED ISSUE #1910: Y24-314 - [BUG] undefined method `name' for nil:NilClass in app/views/labware/_basic_relative.html.erb:7
**Describe the bug**

From [Psd-exceptions] [Limber PRODUCTION] tubes#show (ActionView::Template::Error) "undefined method `name' for nil:NilClass" at 2024-09-12 14:47
```
An ActionView::Template::Error occurred in tubes#show:

  undefined method `name' for nil:NilClass
  app/views/labware/_basic_relative.html.erb:7


-------------------------------
Request:
-------------------------------

  * URL        : https://limber.psd.sanger.ac.uk/limber_tubes/29b9d2ca-6060-11ef-9b63-0242a3ca4cb3
  * HTTP Method: GET
  * IP address : 10.80.242.54
  * Parameters : {"controller"=>"tubes", "action"=>"show", "id"=>"29b9d2ca-6060-11ef-9b63-0242a3ca4cb3"}
  * Timestamp  : 2024-09-12 14:47:42 +0100
  * Server : limb-prod-jammy
    * Rails root : /var/www/limber/releases/20240911130132
  * Process: 681977
```

**RT Ticket Number**
None

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page https://limber.psd.sanger.ac.uk/limber_tubes/29b9d2ca-6060-11ef-9b63-0242a3ca4cb3
2. See the 500 error
3. Check the exception in the mail

This is the labware on sequencescape https://sequencescape.psd.sanger.ac.uk/labware/27573382

This is the grandparent labware: https://limber.psd.sanger.ac.uk/limber_tubes/bb372618-692e-11ef-a75e-024224dd57f4#relatives

**Expected behaviour**
View the labware page in Limber

**Additional context**
Caused by #1641 receiving a labware with no purpose.

_This could be actively preventing pipelines from being processed_

### PR DESCRIPTION
**Pull request by StephenHulme**
Closes #1910 

#### Changes proposed in this pull request

- Add a new Asset relative
- Add link from Asset relative to Sequencescape
- Add check for parent and children to use Asset relative

Screenshot 2024-09-13 at 16 43 35

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

### CODE REVIEW

**Review by sdjmchattie — APPROVED** [review]
You've probably given this more thought than me, so if what you have works and there's no better condition you can apply, I'd say go with it.  However, the condition doesn't feel like it matches with the actions performed.

File: app/views/labware/_child_labware_item.html.erb [hunk 1]
```diff
@@ -10,6 +10,8 @@
   <% else %>
     <%= render partial: 'labware/simple_tube', locals: { tube: labware, open_in_new_window: open_in_new_window } %>
   <% end %>
-<% else %>
+<% elsif labware.purpose.present? %>
```
[the remark this answers is not in the document]
Comment (andrewsparkes) [reply app/views/labware/_child_labware_item.html.erb:13]: Unfortunately Lanes seem to be Labwares with no purposes.

[the remark this answers is not in the document]
Comment (andrewsparkes) [reply app/views/labware/_child_labware_item.html.erb:13]: If he could access `sti_type` that would tell him it was a `Labware::Lane`
