### ISSUE TITLE
Y24-314 - [BUG] undefined method `name' for nil:NilClass in app/views/labware/_basic_relative.html.erb:7

### ISSUE THREAD

**Issue by StephenHulme** [sanger/limber#1910]
**Describe the bug**

From [Psd-exceptions] [Limber PRODUCTION] tubes#show (ActionView::Template::Error) "undefined method `name' for nil:NilClass" at 2024-09-12 14:47
```
An ActionView::Template::Error occurred in tubes#show:

  undefined method `name' for nil:NilClass
  app/views/labware/_basic_relative.html.erb:7


-------------------------------
Request:
-------------------------------

  * URL        : https://limber.psd.sanger.ac.uk/limber_tubes/29b9d2ca-6060-11ef-9b63-0242a3ca4cb3
  * HTTP Method: GET
  * IP address : 10.80.242.54
  * Parameters : {"controller"=>"tubes", "action"=>"show", "id"=>"29b9d2ca-6060-11ef-9b63-0242a3ca4cb3"}
  * Timestamp  : 2024-09-12 14:47:42 +0100
  * Server : limb-prod-jammy
    * Rails root : /var/www/limber/releases/20240911130132
  * Process: 681977
```

**RT Ticket Number**
None

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page https://limber.psd.sanger.ac.uk/limber_tubes/29b9d2ca-6060-11ef-9b63-0242a3ca4cb3
2. See the 500 error
3. Check the exception in the mail

This is the labware on sequencescape https://sequencescape.psd.sanger.ac.uk/labware/27573382

This is the grandparent labware: https://limber.psd.sanger.ac.uk/limber_tubes/bb372618-692e-11ef-a75e-024224dd57f4#relatives

**Expected behaviour**
View the labware page in Limber

**Additional context**
Caused by #1641 receiving a labware with no purpose.

_This could be actively preventing pipelines from being processed_
